from pyramid_debugtoolbar.panels import DebugPanel
from pyramid_debugtoolbar.utils import format_sql as ppq

STATIC_PATH = 'pyramid_straw:static/'


def format_sql(query):
    query = ppq(query)
    query = query.replace(',', ',<br/>')
    query = query.replace('JOIN', '<br/>&nbsp;JOIN')
    return query


class StrawDebugPanel(DebugPanel):
    """
    Panel that displays the SQL generated by SQLAlchemy and the time, memory
     and calling function.
    """
    name = 'straw'
    template = 'pyramid_straw:templates/straw_debugtoolbar.mako'
    title = 'SQLAlchemy Profiler'
    nav_title = 'Straw'

    def __init__(self, request):
        super(StrawDebugPanel, self).__init__(request)
        self.queries = request.straw_data = []

    @property
    def has_content(self):
        if self.queries:
            return True
        else:
            return False

    @property
    def nav_subtitle(self):
        if self.queries:
            return "{} ({:.3f}ms)".format(
                len(self.queries),
                sum(map(lambda x: x['duration'], self.queries))
            )

    def render_vars(self, request):
        return {
            'queries': self.queries,
            'format_sql': format_sql,
            'static_path': '/_debug_toolbar/straw/static/'
        }


def includeme(config):
    config.add_static_view(
        '/_debug_toolbar/straw', STATIC_PATH, static=True)
    config.registry.settings['debugtoolbar.panels'].append(StrawDebugPanel)
    config.commit()
